/**
 * 4tify corporate theme experiences: Metro Vector, Watchtower and Civic Guard.
 * Every mode foregrounds commercial continuity, people, premises, equipment and stock—not residential security.
 */
import { useState } from "react";
import { ArrowRight, Building2, Check, ChevronDown, ClipboardCheck, Clock3, MapPin, Menu, MonitorDot, Phone, Radio, ShieldCheck, Siren, UsersRound, X } from "lucide-react";
import { themeOptions, type ThemeMode } from "./theme";

const media = {
  metro: "/manus-storage/4tify-metro-vector_7fc586a4.webp",
  watchtower: "/manus-storage/4tify-watchtower_35f861d4.webp",
  civic: "/manus-storage/4tify-civic-guard_88be6fa5.webp",
};

const commercialServices = [
  { no: "01", title: "Access Control", copy: "Control entry points, visitor flow and critical zones across your business premises.", icon: ShieldCheck },
  { no: "02", title: "Intelligent CCTV", copy: "Create visibility around stock, equipment, cash points, loading areas and perimeter pressure points.", icon: MonitorDot },
  { no: "03", title: "24/7 Monitoring", copy: "Maintain a professional command posture around alarms, incidents and escalation needs.", icon: Radio },
  { no: "04", title: "On-Site Personnel", copy: "Put trained, accountable security personnel where your operation needs a visible professional presence.", icon: UsersRound },
  { no: "05", title: "Armed Response", copy: "Support a credible response plan for incidents that require decisive escalation.", icon: Siren },
];
const portfolio = ["Guarding", "Access Control", "Investigations", "Risk Analysis", "Patrols", "Casual Guarding", "Cameras", "Pre-Employment Clearance", "Safe Call"];
const locations = [["Benoni", "Head office base"], ["Rynfield", "Rynfield, Benoni"], ["Johannesburg", "Greater Jozi metro"], ["Gauteng", "Province-wide"]];
const businessFaqs = [
  ["Are you registered with PSIRA?", "Yes. 4tify operates under PSIRA Registration 4899123 and is registered as Fourfify Services Gauteng (Pty) Ltd, Company No. 2022/631889/07."],
  ["Which business sites do you cover?", "We support commercial, office, retail, industrial and logistics operations across Benoni, Rynfield, Johannesburg and greater Gauteng."],
  ["Do you provide 24/7 monitoring?", "Our command center is always on alert, ready to dispatch assistance for any security, medical or fire alarm—day or night."],
  ["Can you secure business assets and stock?", "Yes. We build security layers around controlled access, visible deterrence, surveillance, guard presence and operational response."],
  ["Do you offer armed response?", "Yes. We provide rapid, vetted armed-response units ready to deploy the moment a threat is detected."],
  ["How do I request a site assessment?", "Use the contact form below or call us directly on 072 412 3856 for a complimentary, no-obligation assessment."],
];

function Brand({ light = false }: { light?: boolean }) { return <a className={`corp-brand ${light ? "light" : ""}`} href="#home" aria-label="4tify Specialized Security home"><span><i /><i /><i /><i /></span><b>4TIFY<small>Specialized security</small></b></a>; }
function ThemeSelect({ value, onChange, dark = false }: { value: ThemeMode; onChange: (theme: ThemeMode) => void; dark?: boolean }) { return <label className={`theme-select ${dark ? "theme-select-dark" : ""}`}><span>Mode</span><select aria-label="Choose a visual mode" value={value} onChange={(event) => onChange(event.target.value as ThemeMode)}>{themeOptions.map((option) => <option value={option.id} key={option.id}>{option.label}</option>)}</select></label>; }
function DirectActions({ secondary = "Request site assessment" }: { secondary?: string }) { return <div className="direct-actions"><a href="tel:+27724123856"><Phone size={17} />Call 072 412 3856</a><a href="#contact">{secondary}<ArrowRight size={17} /></a></div>; }
function CompanyRecord() { return <div className="company-record"><div><small>Director</small><b>Khethwayo Phillip Zulu</b></div><div><small>Consultant</small><b>Peter Edmund Vosloo</b></div><div><small>PSIRA Registration</small><b>4899123</b></div><div><small>Company Registration</small><b>2022/631889/07</b></div></div>; }
function BusinessForm({ className = "" }: { className?: string }) { return <form className={`business-form ${className}`} action="mailto:phillip.zulu@ymail.com" method="post" encType="text/plain"><label>Full name<input name="name" required placeholder="Your full name" /></label><label>Business email<input name="email" type="email" required placeholder="name@company.co.za" /></label><label>Phone<input name="phone" type="tel" placeholder="Your contact number" /></label><label>Site or requirement<textarea name="message" rows={4} required placeholder="Tell us about your premises, assets or concern" /></label><button type="submit">Request assessment <ArrowRight size={17} /></button><small>Your enquiry opens in your email app.</small></form>; }
function FAQ({ className = "" }: { className?: string }) { return <div className={`corporate-faq ${className}`}>{businessFaqs.map(([question, answer], index) => <details open={index === 0} key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div>; }

export function MetroVector({ theme, onTheme }: { theme: ThemeMode; onTheme: (theme: ThemeMode) => void }) {
  const [open, setOpen] = useState(false);
  return <main className="metro-mode">
    <header className="metro-head"><Brand /><p><i />Gauteng commercial security / business continuity</p><ThemeSelect value={theme} onChange={onTheme} /><button onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></header>
    {open && <nav className="metro-menu">{["Services", "Company", "Coverage", "Questions", "Assessment"].map((item) => <a onClick={() => setOpen(false)} href={`#${item.toLowerCase()}`} key={item}>{item}<ArrowRight size={17} /></a>)}</nav>}
    <section id="home" className="metro-hero"><div className="metro-route-lines" /><div className="metro-copy"><p>Commercial protection / Gauteng</p><h1>Keep the operation <em>moving.</em></h1><p className="metro-lead">Professional security for corporate offices, retail sites, logistics facilities and industrial operations—built around the people, assets and uptime your business depends on.</p><DirectActions secondary="Protect your operation" /><div className="metro-proof"><span><b>24 / 7</b>Command posture</span><span><b>09</b>Core services</span><span><b>PSIRA</b>Reg 4899123</span></div></div><figure><img src={media.metro} alt="Security response vehicle at a commercial business entrance after dark" /><figcaption>Vector 01 // Controlled access and response route</figcaption></figure><aside className="metro-protect"><span>PROTECT</span><b>PEOPLE<br />ASSETS<br />OPERATIONS</b><i /></aside></section>
    <nav className="metro-stop-nav" aria-label="Metro Vector section navigation"><a href="#services"><b>01</b>Secure the site</a><a href="#company"><b>02</b>Know the partner</a><a href="#coverage"><b>03</b>Map the area</a><a href="#contact"><b>04</b>Take action</a></nav>
    <section id="services" className="metro-services"><div className="metro-section-title"><p>Service route // protective stations</p><h2>Security that safeguards the <em>business behind the gate.</em></h2><span>Scroll the route <ArrowRight size={16} /></span></div><div className="metro-service-route">{commercialServices.map((service) => { const Icon = service.icon; return <article key={service.title}><span className="metro-stop-dot" /><b>{service.no}</b><Icon size={25} /><div><h3>{service.title}</h3><p>{service.copy}</p></div><ArrowRight size={18} /></article>; })}</div></section>
    <section className="metro-value"><div><p>Business interests // protected</p><h2>Control at the perimeter. <em>Confidence inside.</em></h2><p>From the first visitor checkpoint to after-hours monitoring, the right security system helps protect stock, equipment, records, facilities teams and the working day itself.</p></div><ol><li><b>01</b><span>Site manager and security briefing</span></li><li><b>02</b><span>Clear instructions for every shift</span></li><li><b>03</b><span>Active reporting before loss occurs</span></li><li><b>04</b><span>Premises, stock and continuity protected</span></li></ol></section>
    <section id="company" className="metro-company"><div className="metro-company-note"><ClipboardCheck size={28} /><p>Company profile // Fourfify Services Gauteng (Pty) Ltd</p><h2>A professional presence with a <em>practical plan.</em></h2><p>4tify is a South African security services provider operating from Benoni, Gauteng. As fellow South Africans, we combine trained personnel, technology and round-the-clock command to help commercial clients protect what keeps their business running.</p><p>Our operating approach respects the officer and the client alike: clear site instructions, accountable shifts, fair published payment timelines, and prompt reporting of danger, loss or property damage.</p><blockquote>“Precautions are better than a cure.”</blockquote></div><CompanyRecord /></section>
    <section className="metro-portfolio"><p>Full service portfolio</p><div>{portfolio.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section>
    <section id="coverage" className="metro-coverage"><div><p>Area of operations // Gauteng</p><h2>Local routes. <em>Broader reach.</em></h2><p>Business protection across Benoni, Rynfield, Johannesburg and greater Gauteng.</p></div><div className="metro-location-grid">{locations.map(([name, detail], index) => <article key={name}><b>{String(index + 1).padStart(2, "0")}</b><MapPin size={18} /><h3>{name}</h3><p>{detail}</p></article>)}</div></section>
    <section id="questions" className="metro-questions"><div><p>Questions // clear answers</p><h2>Know the service. <em>Then make the call.</em></h2><a href="tel:+27724123856"><Phone size={16} />Speak directly</a></div><FAQ /></section>
    <section id="assessment" className="metro-assessment"><div><p>Assessment desk // next action</p><h2>Protect your operation <em>with purpose.</em></h2><p>Request a complimentary, no-obligation site assessment for your Gauteng business.</p><a href="tel:+27724123856">072 412 3856 <Phone size={21} /></a></div><BusinessForm /></section>
    <footer className="metro-footer"><Brand light /><span>© {new Date().getFullYear()} 4tify Services</span><span>Benoni / Johannesburg / Gauteng</span></footer><div className="metro-mobile-dock"><a href="tel:+27724123856"><Phone size={16} />Call</a><a href="#services"><ShieldCheck size={16} />Services</a><a href="#assessment"><ArrowRight size={16} />Assess</a></div>
  </main>;
}

export function Watchtower({ theme, onTheme }: { theme: ThemeMode; onTheme: (theme: ThemeMode) => void }) {
  const [open, setOpen] = useState(false);
  return <main className="watch-mode">
    <section id="home" className="watch-hero"><img src={media.watchtower} alt="Professional security operators monitoring a commercial site and its access points" /><div className="watch-veil" /><header><Brand light /><div><span><i />Observation active</span><ThemeSelect value={theme} onChange={onTheme} dark /><button onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></div></header>{open && <nav className="watch-menu">{["Services", "Company", "Coverage", "Questions", "Assessment"].map((item) => <a onClick={() => setOpen(false)} href={`#${item.toLowerCase()}`} key={item}>{item}<ArrowRight size={17} /></a>)}</nav>}<div className="watch-hero-copy"><p>Watchtower / corporate security intelligence</p><h1>See the risk.<br /><em>Secure the value.</em></h1><p>Professional site protection for business premises, assets, logistics, retail and commercial operations across Gauteng.</p><DirectActions secondary="Request site assessment" /></div><div className="watch-window-label"><span>Live view</span><b>Command / Gauteng</b><i /></div></section>
    <section className="watch-status-bar"><span><i />PSIRA registered / 4899123</span><span><i />Commercial security</span><span><i />24 / 7 command</span><a href="tel:+27724123856"><Phone size={14} />072 412 3856</a></section>
    <section id="services" className="watch-services"><div className="watch-services-intro"><p>Protective observation // service windows</p><h2>Every angle matters to <em>the business.</em></h2><p>Build a clearer picture of access, people, assets and incidents before they become a bigger disruption.</p></div><div className="watch-windows">{commercialServices.map((service, index) => { const Icon = service.icon; return <article key={service.title} className={`watch-window watch-window-${index + 1}`}><div><span>{service.no}</span><Icon size={25} /></div><h3>{service.title}</h3><p>{service.copy}</p><b>Open view <ArrowRight size={15} /></b></article>; })}</div></section>
    <section className="watch-scan"><div className="watch-scan-ring"><i /><i /><i /><b>360°<small>Business<br />protection</small></b></div><div><p>Security posture // business continuity</p><h2>A more complete view of <em>what matters most.</em></h2><div className="watch-scan-list"><span><Check size={16} />Controlled premises and restricted zones</span><span><Check size={16} />People, stock and operational assets</span><span><Check size={16} />Officers respected and accountable for every shift</span><span><Check size={16} />Professional escalation and response planning</span></div></div></section>
    <section id="company" className="watch-company"><div><p>Company profile // local, registered, ready</p><h2>Command starts with a <em>partner you can verify.</em></h2><p>Fourfify Services Gauteng (Pty) Ltd is a South African security services provider operating from Benoni. We combine trained personnel, technology and round-the-clock command around commercial sites that need a disciplined security presence.</p><p>Management meets the assigned site manager to build a way forward that supports client safety and officer safety. Integrity guides financial management, fair employment and respectful working conditions.</p><blockquote>“Precautions are better than a cure.”</blockquote></div><CompanyRecord /></section>
    <section className="watch-portfolio"><span>Service catalogue</span>{portfolio.map((item, index) => <b key={item}><i>{String(index + 1).padStart(2, "0")}</i>{item}</b>)}</section>
    <section id="coverage" className="watch-coverage"><div className="watch-coverage-copy"><p>Coverage window // Gauteng</p><h2>See where the team is <em>positioned to help.</em></h2><p>Operating across Benoni, Rynfield, Johannesburg and greater Gauteng.</p></div><div className="watch-coverage-grid">{locations.map(([name, detail], index) => <article key={name}><span>Zone {String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><p>{detail}</p><MapPin size={18} /></article>)}</div></section>
    <section id="questions" className="watch-faq"><div><p>Control room // questions</p><h2>Information before the <em>next decision.</em></h2><a href="tel:+27724123856">Speak to a professional <Phone size={16} /></a></div><FAQ /></section>
    <section id="assessment" className="watch-contact"><div><p>Open a site assessment</p><h2>Protect the business behind <em>the front gate.</em></h2><p>Tell us about your premises, assets or operational concern. The right response begins with a clear view.</p><a href="tel:+27724123856"><Phone size={19} />072 412 3856</a></div><BusinessForm /></section>
    <footer className="watch-footer"><Brand light /><span>PSIRA REG 4899123</span><span>© {new Date().getFullYear()} 4tify Services</span></footer>
  </main>;
}

export function CivicGuard({ theme, onTheme }: { theme: ThemeMode; onTheme: (theme: ThemeMode) => void }) {
  const [open, setOpen] = useState(false);
  return <main className="civic-mode">
    <div className="civic-notice">Gauteng business protection <i /> Assets / premises / people / continuity <i /> 24 / 7 command posture</div>
    <header className="civic-head"><Brand /><nav><a href="#services">Services</a><a href="#company">Company</a><a href="#coverage">Coverage</a></nav><ThemeSelect value={theme} onChange={onTheme} /><button onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></header>{open && <nav className="civic-menu">{["Services", "Company", "Coverage", "Questions", "Assessment"].map((item) => <a onClick={() => setOpen(false)} href={`#${item.toLowerCase()}`} key={item}>{item}<ArrowRight size={17} /></a>)}</nav>}
    <section id="home" className="civic-billboard"><div className="civic-billboard-copy"><p>4tify / professional commercial security</p><h1>Do not leave your business <em>open to chance.</em></h1><p>Corporate security built to protect facilities, stock, equipment, people and working operations across Gauteng.</p><DirectActions secondary="Protect your business" /><div className="civic-stamp"><b>PSIRA<br />4899123</b><span>Registered<br />Gauteng service</span></div></div><figure><img src={media.civic} alt="CCTV camera protecting a commercial business perimeter" /><figcaption><MonitorDot size={19} />Asset visibility // controlled access</figcaption></figure><div className="civic-corner">BUSINESS<br />INTERESTS<br />SECURED</div></section>
    <section id="services" className="civic-kit"><div className="civic-kit-title"><p>Security kit // what protects the operation</p><h2>Fast facts. <em>Clear protective layers.</em></h2><span>Open the kit <ArrowRight size={16} /></span></div><div className="civic-kit-sheets">{commercialServices.map((service) => { const Icon = service.icon; return <article key={service.title}><div><span>{service.no}</span><Icon size={27} /></div><h3>{service.title}</h3><p>{service.copy}</p><b>Protect <ArrowRight size={15} /></b></article>; })}</div></section>
    <section className="civic-interest"><div><p>Security with heart // why it matters</p><h2>Security supports the value <em>you have built.</em></h2><p>Effective site protection is about more than an alarm. It gives you a visible, managed response around the assets, access points and people that keep your operation functioning—delivered by fellow South Africans serving the wider community.</p><a href="#assessment">Request a site plan <ArrowRight size={17} /></a></div><div className="civic-interest-board"><span>Integrity</span><span>Officer respect</span><span>Fair employment</span><span>Shift ownership</span><span>Risk reporting</span><span>Prevention first</span></div></section>
    <section id="company" className="civic-profile"><figure><div className="civic-profile-badge">LOCAL<br />READY<br />REGISTERED</div><img src={media.metro} alt="Private-security vehicle ready at a commercial entry point" /></figure><div><p>Company record // Fourfify Services Gauteng (Pty) Ltd</p><h2>Visible protection. <em>Accountable service.</em></h2><p>4tify is a South African security services provider operating from Benoni, Gauteng. We bring trained personnel, technology and command discipline together to protect commercial sites and the interests they represent.</p><p>Each officer is responsible for their own shift: arriving on time, fulfilling the agreed site instructions, and reporting activity that could lead to danger, loss or damage.</p><CompanyRecord /><blockquote>“Precautions are better than a cure.”</blockquote></div></section>
    <section className="civic-portfolio"><p>Full service portfolio</p><div>{portfolio.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section>
    <section id="coverage" className="civic-coverage"><div><p>Where we operate // Gauteng</p><h2>Commercial focus. <em>Local reach.</em></h2><p>Operating throughout Benoni, Rynfield, Johannesburg and greater Gauteng.</p></div><ol>{locations.map(([name, detail], index) => <li key={name}><b>{String(index + 1).padStart(2, "0")}</b><span><strong>{name}</strong><small>{detail}</small></span><MapPin size={18} /></li>)}</ol></section>
    <section id="questions" className="civic-questions"><div className="civic-question-title"><p>Questions // practical answers</p><h2>Get the facts. <em>Protect the next move.</em></h2><a href="tel:+27724123856"><Phone size={16} />072 412 3856</a></div><FAQ /></section>
    <section id="assessment" className="civic-contact"><div><p>Assessment slip // start here</p><h2>Secure the site. <em>Protect the value.</em></h2><p>Request a complimentary, no-obligation assessment for your business premises.</p><a href="tel:+27724123856">Direct call <Phone size={19} /></a></div><BusinessForm /></section>
    <footer className="civic-footer"><Brand light /><span>© {new Date().getFullYear()} 4tify Services</span><span>Benoni / Johannesburg / Gauteng</span></footer><a className="civic-mobile-action" href="#assessment">Request assessment <ArrowRight size={17} /></a>
  </main>;
}
